name: New Attribute Request
description: Request to add a new attribute to a template or data model
title: "[NewAttribute]: "
labels: ["newAttribute"]
projects: ["ELITE", "dataModel"]
assignees:
  - nicholas.lee
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new attribute request!
  - type: textarea
    id: new-attribute
    attributes:
      label: What new attribute(s) is needed?
      description: Is there a missing attribute you want to add or update is needed?
      placeholder: Tell us what you see!
      value: "A new attribute is needed"
    validations:
      required: true
  - type: dropdown
      id: change-type
      attributes:
        label: Version
        description: What type of change is needed?
        options:
          - New
          - Update
        default: 0
      validations:
        required: true
