name: Request to add or update template in the data model
description: Changes to the data model to be incorporated
title: "[dataModelUpdate]: "
labels: ["template"]
projects: ["ELITE", "dataModel"]
assignees:
  - nicholas.lee

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: dropdown
    id: change-type
    attributes:
      label: Change Type
      description: Name of the template
      options: 
        - Update
        - Addition
      default: Update
    validations:
      required: true
  - type: input
    id: dataType
    attributes:
      label: Template to add or update
      description: Name of the template
      placeholder: ex. proteomics
    validations:
      required: true
  - type: input
    id: rfcLink
    attributes:
      label: RFC Link
      description: Link to the RFC to add / update for the data model
      placeholder: ex. https://docs.google.com/spreadsheets/
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Additional Comments
      description: Anything else to add? 
      placeholder: Tell us what we should know about this addtion
      value: "A bug happened!"
    validations:
      required: false
