# GitHub Action to create a DCA template config json file for a data model

# This action should be run manually after: adding, removing, or renaming any manifest templates in the json-ld data model, and successful completion of `update_data_model.yml`
# This action should run before: using a new template in the Data Curator App
# * this action must be triggered manually and the resulting PR must be reviewed and merged to complete the template config changes
# 
# This action creates a json file named with the `file` input argument using 
# the data model supplied to the `data_model` argument. It will validate the 
# json file against DCA's template config schema. Finally, it will create a PR
# in the repo for the new file.
#
# Copy this into your data model repo .github/workflow directory.
# Your repo settings must have Actions enabled and must allow GitHub Actions to
# create and approve pull requests.
# 
# By default, this action runs by workflow dispatch. But it can be configured
# to run on other triggers. Consult the github doc below for more information.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
#
# The resulting file will contain one entry for each attribute in the data model that `dependsOn`
# "Component". To include a subset of these attributes, use either `include_schemas` or
# `exclude_schemas` in the call to `datacurator::write_dca_template_config()`. The "type" parameter 
# for each template will be `file` if the `DependsOn` column for that template includes the 
# attribute "Filename"; if not the type will be `record`. 
#
# --------------------------------------------------------------------------------------------------

name: DCA Template Config File
on:
  workflow_dispatch:
    inputs:
      data_model:
        description: URL to a jsonld data model file
        required: true
        default: 'https://raw.githubusercontent.com/eliteportal/data-models/reinstate-workflows/EL.data.model.jsonld'
      file:
        description: File name path to save the template config
        required: true
        default: 'dca-template-config.json'
      data_model_labels:
        description: How schematic reads data model labels. Default 'class_label'. Can also be 'display_label'.
        required: true
        default: 'class_label'
      include_schemas:
        description: Space-separated string of schemas to include in output. Must be empty if using exclude_schemas.
        required: false
      exclude_schemas:
        description: Space-separated string of schemas to exclude from output. Must be empty if using include_schemas.
        required: false

jobs:
  create-template-config:
    runs-on: ubuntu-latest
    env: 
      FILE: dca-template-config.json
    steps:
      - uses: actions/checkout@v4

      - name: Checkout DCA Config Repo for Schema
        uses: actions/checkout@v4
        with:
          repository: 'Sage-Bionetworks/data_curator_config'
          ref: 'dev'
          path: 'data_curator_config'

      - name: Create config file
        uses: sage-bionetworks/dca-template-config-action@main
        env:
          data_model: ${{ inputs.data_model }}
          file: ${{ inputs.file }}
          include_schemas: ${{ inputs.include_schemas }}
          exclude_schemas: ${{ inputs.exclude_schemas }}
          data_model_labels: ${{ inputs.data_model_labels }}
        
      - name: Validate Config File
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: 'data_curator_config/schemas/dca_template_config.schema.json'
          INPUT_JSONS: ${{ inputs.file }}
      
      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update DCA Template Config File
          body: Recreate the json file that populates the DCA template dropdown menu.
          delete-branch: true
          branch-suffix: timestamp
          add-paths: |
            ${{ inputs.file }}
