# This workflow automatically generates all manifests currently specified by the data model
# Outputs are excel files and json schemas
# Runs AFTER changes to the data model have been reviewed in a PR and merged into main

name: Store Current Manifests

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  generate:
    name: generate-and-upload-manifests
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SCHEMATIC_SERVICE_ACCOUNT_CREDS: ${{ secrets.SCHEMATIC_SERVICE_ACCOUNT_CREDS }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_TOKEN_DPE }}
      #SYNAPSE_UPLOAD_FOLDER_ID: syn25878249

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          poetry install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "GitHub Action: generate latest manifests"
          title: "Update manifests"
          body: |
            This PR updates the manifests based on the latest changes.
            Please review and merge if everything looks correct.
          branch: update-manifests
          base: main
          labels: |
            automated pr
            manifest update
          reviewers: $$ {github.actor }}
          draft: false
          delete-branch: true

      #- name: Upload all manifests
      #  working-directory: elite-data/manifest-templates
      #  run: ../tests/upload_templates.sh