# This workflow automatically generates all manifests currently specified by the data model
# Outputs are excel files and json schemas
# Runs AFTER changes to the data model have been reviewed in a PR and merged into main

name: Store Current Manifests

on:
  push:
    branches: schematic-228-template-workflow

  workflow_dispatch:
  
jobs:
  generate:
    name: generate-and-upload-manifests
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SCHEMATIC_SERVICE_ACCOUNT_CREDS: ${{ secrets.SCHEMATIC_SERVICE_ACCOUNT_CREDS }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_TOKEN_DPE }}
      SYNAPSE_UPLOAD_FOLDER_ID: syn64504390

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry install

      - name: Generate all manifests
        working-directory: processes
        run: poetry run ./generate_all_templates.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "GitHub Action: generate latest manifests"
          title: "Update manifests"
          body: |
            This PR updates the manifests based on the latest changes.
            Please review and merge if everything looks correct.
          branch: update-manifests
          base: main
          labels: |
            automated pr
            manifest update
          draft: true
          delete-branch: false

      - name: Upload all manifests
        working-directory: elite-data/manifest-templates
        run: poetry run ../../processes/upload_templates.sh