# Updates the metadata dictionary that is @ https://eliteportal.github.io/data-dictionary/

name: update_metadata_dictionary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: update term files and pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: update _data csv term files
        run: |
          poetry run python processes/data_manager.py

      - name: update term pages
        run: |
          poetry run python processes/page_manager.py
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated dictionary term files and term pages'
