# This workflow is used to convert changed EL.data.model.csv to EL.data.model.jsonld
# It will run any time a PR is opened that includes changes to the 'modules/' directory
# Before this: manually or programmatically editing the module csvs and opening a PR
# After this: merging the PR to main will update the dictionary site files (update_metadata_dictionary.yml)

name: Update Data Model

on:
  pull_request:
   branches: main
    # runs on changes to module csvs
   paths: 'modules/**'

  workflow_dispatch:

jobs:
  CI:
    name: update-data-model
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
  
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install

    - name: Join data model and convert to json-ld
      run: |
        poetry run python data_model_creation/join_data_model.py
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Github Action: Joined modules and converted to json-ld data model'