name: Update data dictionary

on: workflow_dispatch

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: update term files and pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: bash
        run: |
          pip3 install poetry
          poetry build

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: update term file if data model csv is changed
        if: contains(steps.changed-files.outputs.modified_files, 'EL.data.model.csv')
        run: |
          python data-dictionary/scripts/file_manager.py
