# This workflow is used to convert changed EL.data.model.csv to EL.data.model.jsonld
# and push the updated ELITE.data.model.jsonld to feature branch
# intended to be used after updating the individual modules

name: Update Data Model

on:
  pull_request:
    branches: main
    # runs on changes to module csvs
    paths: 'modules/**'
  workflow_dispatch:
jobs:
  CI:
    name: schema-convert
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Schematic
        shell: bash
        run: |
          pip3 install poetry
          git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
          cd schematic
          poetry build
          pip3 install dist/schematicpy-*-py3-none-any.whl

      - name: Join data model
        shell: bash
        run: |
          pip install thefuzz  
          data_model_creation/update_data_model.sh
        
      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit the changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add . 
          git commit -m "GitHub Action: join modules into csv and convert *.model.csv to *.model.jsonld" || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save model creation and conversion logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: creation-conversion-logs
          path: _logs
